# -*- coding: utf-8 -*-
"""Walmart Cleaned Set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgXxC-_gX2d1e-T8oFYT-e251l1XdKHo

Import libraries
"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_excel("/content/walmart_supply_chain_dataset.xlsx")

# Copy dataset
clean_df = df.copy()

# Standardize column names
clean_df.columns = clean_df.columns.str.strip().str.lower().str.replace(" ", "_")

# Handle missing values
text_cols = ["product_name", "category", "warehouse", "region", "supplier", "disruption_type"]
for col in text_cols:
    clean_df[col] = clean_df[col].fillna("Unknown")

num_cols = ["stock_level", "units_sold", "demand_forecast", "lead_time",
            "cost_per_unit", "selling_price", "transportation_cost", "delay_flag"]
for col in num_cols:
    clean_df[col] = clean_df[col].fillna(clean_df[col].median())

# Convert date
clean_df["date"] = pd.to_datetime(clean_df["date"], errors="coerce")
clean_df = clean_df.dropna(subset=["date"])

# Remove duplicates
clean_df = clean_df.drop_duplicates()

# Standardize text formatting
clean_df["category"] = clean_df["category"].str.strip().str.title()
clean_df["warehouse"] = clean_df["warehouse"].str.strip().str.title()
clean_df["region"] = clean_df["region"].str.strip().str.title()
clean_df["supplier"] = clean_df["supplier"].str.strip().str.title()
clean_df["disruption_type"] = clean_df["disruption_type"].str.strip().str.title()
clean_df["product_name"] = clean_df["product_name"].str.strip().str.title()

# Remove invalid numeric values
clean_df = clean_df[clean_df["stock_level"] >= 0]
clean_df = clean_df[clean_df["units_sold"] >= 0]
clean_df = clean_df[clean_df["demand_forecast"] >= 0]
clean_df = clean_df[clean_df["lead_time"] >= 0]
clean_df = clean_df[clean_df["cost_per_unit"] >= 0]
clean_df = clean_df[clean_df["selling_price"] >= 0]
clean_df = clean_df[clean_df["transportation_cost"] >= 0]

# Fix delay flag
clean_df["delay_flag"] = clean_df["delay_flag"].apply(lambda x: 1 if x == 1 else 0)

# Create new columns
clean_df["year"] = clean_df["date"].dt.year
clean_df["month"] = clean_df["date"].dt.month
clean_df["month_name"] = clean_df["date"].dt.month_name()
clean_df["quarter"] = clean_df["date"].dt.quarter
clean_df["inventory_value"] = clean_df["stock_level"] * clean_df["cost_per_unit"]
clean_df["revenue"] = clean_df["units_sold"] * clean_df["selling_price"]
clean_df["profit"] = clean_df["units_sold"] * (clean_df["selling_price"] - clean_df["cost_per_unit"])
clean_df["forecast_error"] = clean_df["demand_forecast"] - clean_df["units_sold"]
clean_df["stock_status"] = np.where(clean_df["stock_level"] < clean_df["units_sold"], "Stockout Risk", "Sufficient")

# Save cleaned dataset
clean_df.to_excel("walmart_supply_chain_dataset_cleaned.xlsx", index=False)

print("Data cleaned successfully.")
print(clean_df.head())
print(clean_df.shape)